# deployment/docker-compose.yml

version: '3.8'
services:
  backend:
    build:
      context: ../backend
    container_name: shopping-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://kaviyadharshinim3:zmcnB46jF0crUSoF@kaviya.kg8srtu.mongodb.net/test?retryWrites=true&w=majority
      - JWT_SECRET=your_secret_key
    restart: always

  frontend:
    build:
      context: ../frontend
    container_name: shopping-frontend
    ports:
      - "3000:3000"
    restart: always
